#!/bin/bash
ICONS=`/usr/bin/defaults read com.apple.finder CreateDesktop`
if [ $ICONS == false ]; then
  defaults write com.apple.finder CreateDesktop true
  killall Finder
  echo "Desktop icons are now visible"
elif [ $ICONS == true ]; then
  defaults write com.apple.finder CreateDesktop false
  killall Finder
  echo "Desktop icons are now hidden"
fi
